name: audio_book_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_screenutil: ^0.5.3
  carousel_slider: ^2.2.1
  charts_flutter: ^0.9.0
  dio: ^3.0.0
  path_provider: ^1.6.24
  cookie_jar: ^1.0.1
  shared_preferences: ^0.5.12+4
  connectivity: ^2.0.2
  dio_cookie_manager: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/bookPic_1.png
    - images/bookPic_2.png
    - images/bookPic_3.png
    - images/shopping_bag.png
    - images/icon_royal.png
    - images/icon_right_green.png
    - images/icon_circle_green.png
    - images/icon_select.png
    - images/icon_toUp.png
    - images/icon_play.png
    - images/star.png
    - images/halfStar.png
    - images/isLike.png
    - images/unlike.png
    - images/course_top.png
    - images/icon_pause.png
    - images/star_gold.png
    - images/halfStar_gold.png
    - images/goldCoin.png
    - images/icon_undone.png
    - images/icon_clap_white.png
    - images/icon_clap_green.png
    - images/action_clap_green.png
    - images/action_clap_white.png
    - images/icon_pen.png
    - images/icon_share.png
    - images/icon_clap_big.png
    - images/icon_delete.png
    - images/gold_book.png
    - images/blue_word.png
    - images/bookshelf_word.png
    - images/icon_toDown.png
    - images/light.png
    - images/star_white.png
    - images/star_transparent.png
    - images/icon_green_pen.png
    - images/icon_arrow_right.png
    - images/icon_brown_play.png
    - images/icon_console.png
    - images/icon_backone.png
    - images/icon_underline.png
    - images/icon_playArticle.png
    - images/icon_write.png
    - images/icon_shareArticle.png
    - images/note_pic.png
    - images/icon_pause_brown.png
    - images/icon_font.png
    - images/icon_theme.png
    - images/icon_more.png
    - images/icon_arrow_right2.png
    - images/bgLight.png
    - images/arrow_circle_right.png
    - images/goldenmint_finish.png
    - images/select_right_green.png
    - images/mint_top.png
    - images/mint_button_coin.png
    - images/mint_title1.png
    - images/mint_title2.png
    - images/mint_change_book.png
    - images/icon_close.png
    - images/icon_now.png
    - images/icon_done.png
    - images/icon_fail.png
    - images/more_book.png
    - images/banner.png
    - images/wish1.png
    - images/wish2.png
    - images/wish3.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Charter
      fonts:
        - asset: assets/font/Charter.ttc
    - family: NewYork
      fonts:
        - asset: assets/font/NewYork.otf
    - family: ArialBlack
      fonts:
        - asset: assets/font/ArialBlack.TTF
#     - family: Schyler
#       fonts:
#         - asset: fonts/Schyler-Regular.ttf
#         - asset: fonts/Schyler-Italic.ttf
#           style: italic
#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700
#     - family: Charter
#       fonts:
#         - asset: assets/font/Charter.ttc
#     - family: NewYork
#       fonts:
#         - asset: assets/font/NewYork.otf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
